<<<<<<< HEAD
# Generated by Django 4.2 on 2023-04-25 08:29
=======
# Generated by Django 4.2 on 2023-04-25 09:05
>>>>>>> 42455f038cdd190823f4a90ba8a2317a7b2c3a32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_delivery", models.BooleanField(default="False")),
                ("is_paid", models.BooleanField(default="False")),
                ("total", models.IntegerField(default=0)),
                ("date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Completed", "Completed")],
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PickUp", "PickUp"), ("Delivery", "Delivery")],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[("Disabled", "Disabled"), ("Enabled", "Enabled")],
                        max_length=50,
                    ),
                ),
                ("price", models.FloatField()),
                ("image", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Foods", "Foods"),
                            ("Drinks", "Drinks"),
                            ("Refreshments", "Refreshments"),
                            ("Sale off Dishes", "Sale off Dishes"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.CharField(max_length=200)),
                ("image", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('details', models.CharField(default='', max_length=100)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.cart')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.dish')),
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("details", models.CharField(default="", max_length=100)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="res.cart"
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="res.dish"
                    ),
                ),
>>>>>>> 42455f038cdd190823f4a90ba8a2317a7b2c3a32
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("number_phone", models.TextField(max_length=10)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="res.menu"
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("number_phone", models.TextField(max_length=10)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="res.customer"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="res.employee"
            ),
        ),
    ]
