# Generated by Django 4.2 on 2023-04-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food',
            new_name='dish',
        ),
    ]
