# Generated by Django 4.2 on 2023-04-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("res", "0002_customer_employee_food_menu_order_pickup_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(null=True, upload_to="foods/"),
        ),
    ]
