# Generated by Django 4.2 on 2023-04-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_alter_cart_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disk',
            new_name='Dish',
        ),
    ]
